apiVersion: v1
kind: Service
metadata:
  name: courier-service
spec:
  selector:
    app: courier-service
  ports:
    - protocol: TCP
      port: 3000 # Exposed port on the service
      targetPort: 3000 # Port on the pod where the service will forward traffic
