apiVersion: v1
kind: Service
metadata:
  name: h2
spec:
  ports:
    - port: 8082
      targetPort: 8082
      name: web
    - port: 9092
      targetPort: 9092
      name: tcp
  selector:
    app: h2
  type: ClusterIP
