apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments # Match the app label from the deployment
  ports:
    - protocol: TCP
      port: 3000 # Exposed port on the service
      targetPort: 8080 # Port on the pod where the service will forward traffic
