apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3000 # Exposed port on the service
      targetPort: 8080 # Port on the pod where the service will forward traffic
